name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
   

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
            ssh  -o StrictHostKeyChecking=no ubuntu@54.90.29.10 << 'EOF'
            mkdir -p ~/akintayo-portfolio/ 
            cd ~/akintayo-portfolio/
            if [ ! -d ".git"]; then
              echo "Not a Git repository. Initializing..."
              git init 
              git remote add origin git@github.com:tech-tailor/akintayo-portfolio.git
            fi
            git reset --hard HEAD
            git pull origin main"
            flask --app portfolio run --debug --host 0.0.0.0            
          EOF
        

      - name: Create git directory
        run: |
          


        

      - name: Check deployment
        run: |
          echo "deployed"
