name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to Server
        run: |
          ssh ${{ secrets.SERVER_ADDRESS }} "mkdir -p ~/akintayo-portfolio/"
          scp -r ./ ${{ secrets.SERVER_ADDRESS }}:~/akintayo-portfolio/

      - name: Check deployment
        echo "deployed"
